version: '3.1'

services:
    microservdb:
        image: postgres:9.6.3
        container_name: microservdb
        command: postgres -c log_statement=all
        environment:
            POSTGRES_USER_FILE: /run/secrets/postgres_username
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
            POSTGRES_DB: microserv
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
          - "5432:5432"
        secrets:
          - postgres_username
          - postgres_password
    security:
        image: nderwin/security:1.0.0-SNAPSHOT
        container_name: security
        depends_on:
          - "microservdb"
        ports:
          - "8080:8080"
          - "9990:9990"

secrets:
    postgres_username:
        file: ./dockersecrets/postgres_username
    postgres_password:
        file: ./dockersecrets/postgres_password
